# config file version
apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  url: http://172.18.0.21:9090
  access: proxy
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: '20s'
- name: alertmanager
  type: alertmanager
  orgId: 1
  typeLogoUrl: public/img/icn-datasource.svg
  access: proxy
  url: http://127.0.0.1:9093
  password: 
  user: 
  database: 
  basicAuth: 
  isDefault: 
  jsonData:
    implementation: 'prometheus'
